# Site settings
title: Minh Kieu's Homepage
tagline: ""
keywords: 
description: > # this means to ignore newlines until "baseurl:"
    "Minh Kieu web"

# For the web
url:      ""
baseurl:  ""

# Define how blog permalinks should be constructed
permalink: /:year/:month/:title.html
# (the default:)
#permalink: /:categories/:year/:month/:day/:title.html


author :
  name : Minh Kieu
  github : leminhkieu
  twitter : minhkieu


twitter_username: leminhkieu
github_username:  leminhkieu
email: m.l.kieu@leeds.ac.uk

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
